import type { Metadata } from "next";
import "./globals.css";
import Navber from "./shared/Navber/Navber";
import NextAuthSessionProvider from "./providers/NextAuthSessionProvider";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
         <body
           className={`${geistSans.variable} ${geistMono.variable} antialiased w-max-[1440px] mx-auto min-h-screen bg-slate-50`}
         >
           <Navber/>
           {children}
         </body>
      </NextAuthSessionProvider>
    </html>
  );
}
