import type { Metadata } from "next";
import "./globals.css";
import Navber from "./shared/Navber/Navber";
import NextAuthSessionProvider from "./providers/NextAuthSessionProvider";
import { Poppins } from "next/font/google";
import Footer from "./shared/Footer/Footer";
import QueryProvider from "./providers/QueryProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <head><link rel="icon" href="/favicon.ico" /></head>
      <QueryProvider>
        <NextAuthSessionProvider>
           <body className={`${poppins.className} antialiased w-max-[1440px] mx-auto min-h-screen bg-slate-100`} >
            <main>
              <Navber/>
              {children}
            </main>
            <Footer/>
           </body>
        </NextAuthSessionProvider>
      </QueryProvider>
    </html>
  );
}
