import type { Metadata } from "next";
import "./globals.css";
import Navber from "./shared/Navber/Navber";
import { Poppins } from "next/font/google";
import Footer from "./shared/Footer/Footer";

export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <head><link rel="icon" href="/favicon.ico" /></head>
        <body className={`${poppins.className} antialiased w-max-[1440px] mx-auto min-h-screen bg-slate-100`} >
         <main>
           <Navber/>
           {children}
         </main>
         <Footer/>
        </body>
    </html>
  );
}
